### ISSUE TITLE
error in import kxy

### ISSUE THREAD

**Issue by zeydabadi** [kxytechnologies/kxy-python#2]
Hi,
After installing the kxy package and configuring the API key, the `import kxy` shows the error below:

```
.../python3.9/site-packages/kxy/pfs/pfs_selector.py in <module>
      6 import numpy as np
      7 
----> 8 import tensorflow as tf
      9 from tensorflow.keras.callbacks import EarlyStopping, TerminateOnNaN
     10 from tensorflow.keras.optimizers import Adam

ModuleNotFoundError: No module named 'tensorflow'

```

what version of tensorflow is needed for kxy to work?

**Comment by ylks** [comment]
Hello,

Tensorflow isn't included in the requirements of the Python package as it is only required by the pfs submodule. 

**You should be good to go with version 2.8.0.**

For future reference, you can find the complete list of requirements in the docker file: https://github.com/kxytechnologies/kxy-python/blob/master/docker/kxy/Dockerfile.

Yves-Laurent

**Comment by zeydabadi** [comment]
Thanks for your response, that seems to solve the problem.
