### ISSUE TITLE
generate_features Documentation?

### ISSUE THREAD

**Issue by ddofer** [kxytechnologies/kxy-python#4]
Is there any documentation on how to use the `generate_features` function? It doesn't appear in the documentation and I can't find it in the github. e.g. how to use the entity column, how to format time-series data in advance for it, etc'. 
Thanks!

**Comment by drylks** [comment]
Hey @ddofer,

Feature transformations are implemented in [this file](https://github.com/kxytechnologies/kxy-python/blob/master/kxy/pandas_extension/features_accessor.py).

You'll also find the documentation on the documentation website [here](https://kxy.ai/reference/latest/pandas/index.html#).

Yves-Laurent
